#!/bin/bash

# Get timestamp and version for release
current_time=`date -u "+%Y-%m-%d %H:%M:%S"`
current_timestamp=$[10#$(date -d "$current_time" -u +%s)]
echo now time utc is: $current_time
echo now time utc second is: $current_timestamp
package_library_version=`cat ./json_config/version.txt`
package_kicad_version=`cat ./json_config/kicad_version.txt`
echo current library version is: $package_library_version
echo current kicad_version version is: $package_kicad_version
installed_size=`du -sb ./`
installed_size=${installed_size%%./*}
installed_size=${installed_size//[[:blank:]]/}


# Change metadata.json file
version_string="            \"version\": \"$package_library_version\",\n"
kicad_version_string="            \"kicad_version\": \"$package_kicad_version\"\n"
status_string="            \"status\": \"stable\",\n"
package_status_string=${version_string}${status_string}${kicad_version_string}
target_string="\"versions\": ["
sed -i "s/\"versions\": \[/&\n        {\n${package_status_string}        }/" metadata.json
zip -r -q PackageLIB.zip resources/ symbols/ footprints/ 3dmodels/ metadata.json

# Modify packages.json file
package_size=`wc -c ./PackageLIB.zip`
package_size=${package_size%% ./*}
packagelib_sha256=`sha256sum ./PackageLIB.zip`
packagelib_sha256=${packagelib_sha256%%  *}
download_sha_string="                    \"download_sha256\": \"$packagelib_sha256\",\n"
download_size_string="                    \"download_size\": \"$package_size\",\n"
installed_size_string="                    \"install_size\": \"$installed_size\",\n"
downloadurl_string="                    \"download_url\": \"https:\/\/github.com\/PackageLAN\/PackageLIB\/releases\/download\/version$package_library_version\/PackageLIB.zip\",\n"
version_string="                    \"version\": \"$package_library_version\",\n"
kicad_version_string="                    \"kicad_version\": \"$package_kicad_version\"\n"
status_string="                    \"status\": \"stable\",\n"
package_descryp_string=${download_sha_string}${download_size_string}${downloadurl_string}${installed_size_string}
package_status_string=${version_string}${status_string}${kicad_version_string}
echo package size is: ${package_size} B
echo installed size is: ${installed_size} B
sed -i "s/\"versions\": \[/&\n                {\n${package_descryp_string}${package_status_string}                },/" ./json_config/packages.json



# Package zip and calculate check value
resources_sha256=`sha256sum ./json_config/resources.zip`
resources_sha256=${resources_sha256%%  *}
packages_sha256=`sha256sum ./json_config/packages.json`
packages_sha256=${packages_sha256%%  *}
echo resources: $resources_sha256
echo packages: $packages_sha256

